# Generated by Django 5.2.17 on 2026-08-10 02:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('queued', 'Queued'), ('validating', 'Validating'), ('extracting_text', 'Extracting text'), ('running_ocr', 'Running OCR'), ('classifying', 'Classifying'), ('extracting_fields', 'Extracting structured data'), ('validating_extraction', 'Validating extraction'), ('scoring_confidence', 'Scoring confidence'), ('indexing', 'Indexing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=32)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('is_retryable', models.BooleanField(default=False)),
                ('error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('error_message', models.CharField(blank=True, max_length=500, null=True)),
                ('document_type', models.CharField(blank=True, choices=[('invoice', 'Invoice'), ('contract', 'Contract'), ('receipt', 'Receipt'), ('report', 'Report'), ('policy', 'Policy'), ('form', 'Form'), ('unknown', 'Unknown')], max_length=16, null=True)),
                ('total_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('ocr_page_count', models.PositiveIntegerField(default=0)),
                ('raw_text_excerpt', models.CharField(blank=True, max_length=2000)),
                ('correlation_id', models.CharField(blank=True, max_length=64)),
                ('stage_history', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='documents.document')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document', '-created_at'], name='processing__documen_629f95_idx'), models.Index(fields=['workspace', '-created_at'], name='processing__workspa_dd2247_idx')],
            },
        ),
    ]
