# Generated by Django 5.2.17 on 2026-08-12 10:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notify_on_approval_requested', models.BooleanField(default=True)),
                ('notify_on_document_processed', models.BooleanField(default=True)),
                ('webhook_notifications_enabled', models.BooleanField(default=True)),
                ('auto_classify_enabled', models.BooleanField(default=True)),
                ('document_retention_days', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_text_retention_days', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='workspaces.workspace')),
            ],
        ),
    ]
