# Generated by Django 5.2.17 on 2026-08-12 04:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentExtraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_review', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('overall_confidence', models.FloatField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction', to='documents.document')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=128)),
                ('display_value', models.CharField(blank=True, max_length=500)),
                ('normalized_value', models.CharField(blank=True, max_length=500)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('bounding_box', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='extraction.documentextraction')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='FieldCorrection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('before_value', models.CharField(blank=True, max_length=500)),
                ('after_value', models.CharField(blank=True, max_length=500)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('corrected_at', models.DateTimeField(auto_now_add=True)),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='extraction.extractedfield')),
            ],
            options={
                'ordering': ['-corrected_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('message', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='extraction.documentextraction')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='extraction.extractedfield')),
            ],
            options={
                'ordering': ['severity', 'code'],
            },
        ),
        migrations.AddIndex(
            model_name='documentextraction',
            index=models.Index(fields=['workspace', 'status', '-created_at'], name='extraction__workspa_36b3ab_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedfield',
            index=models.Index(fields=['extraction', 'key'], name='extraction__extract_4470e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='extractedfield',
            constraint=models.UniqueConstraint(fields=('extraction', 'key'), name='unique_field_per_extraction'),
        ),
        migrations.AddIndex(
            model_name='fieldcorrection',
            index=models.Index(fields=['field', '-corrected_at'], name='extraction__field_i_4a7d74_idx'),
        ),
        migrations.AddIndex(
            model_name='validationissue',
            index=models.Index(fields=['extraction', 'severity'], name='extraction__extract_4705cf_idx'),
        ),
    ]
